"""A0 — DATA correctness for the six-year no-file date (validate the data, not the
filter that sits on top of it). Offline, against committed REAL fixtures:

  tests/fixtures/data_protection/register_active_sample.html — the real Active
      Data Protection table, saved verbatim from the live Register page.
  tests/fixtures/data_protection/dp_join_products.json — the real DPD-product →
      6-year-date join produced by the production matcher over the whole universe.

Both are regenerated by tests/scripts/build_dp_register_fixture.py (network).

Asserts: the scrape parses the right column for hand-verified named rows; the date
attaches to the right DIN; a no-Register product stays blank; a near-miss
manufacturer does NOT receive a false date; and — the fuzzy-match-at-scale guard —
the whole-universe join attaches no fabricated date, fans out within a sane bound,
attaches no more distinct (ingredient, manufacturer) identities than Register rows
exist, and every attached DIN shares its Register row's normalized identity.
"""
from __future__ import annotations

import json
from collections import Counter
from datetime import date
from difflib import get_close_matches
from pathlib import Path

import pytest
from bs4 import BeautifulSoup

from app.enrichment.data_protection import (
    _find_active_table,
    _normalize_ingredient_dp as NI,
    _normalize_manufacturer as NM,
    _parse_data_protection_table,
)
from app.enrichment.screen import parse_stored_no_file_date
from app.enrichment.workbook import _get_dp_cols

_FIX = Path(__file__).parent / "fixtures" / "data_protection"
_HTML = _FIX / "register_active_sample.html"
_JOIN = _FIX / "dp_join_products.json"

pytestmark = pytest.mark.skipif(
    not _HTML.exists() or not _JOIN.exists(),
    reason="dp fixtures missing — run python -m tests.scripts.build_dp_register_fixture",
)

# Hand-verifiable anchors on the live Register page (Active Data Protection table).
_REGISTER_ANCHORS = {
    "clesrovimab": ("Merck Canada Inc.", "2032-01-30"),
    "abemaciclib": ("Eli Lilly Canada Inc.", "2025-04-05"),
    "abrocitinib": ("Pfizer Canada ULC", "2028-06-29"),
}
# Fan-out ceiling: live max observed was 18 DINs per (date, manufacturer); a single
# innovator legitimately covers several strengths/DINs. A blowup well past this
# signals a fuzzy-match regression cross-attaching one Register row everywhere.
_FANOUT_CEILING = 40


def _dp_table() -> list[dict]:
    soup = BeautifulSoup(_HTML.read_text(encoding="utf-8"), "html.parser")
    return _parse_data_protection_table(_find_active_table(soup))


def _join() -> dict:
    return json.loads(_JOIN.read_text(encoding="utf-8"))


# ════════════════════════════════════════════════════════════════════════════
# Scrape parse — right column, verbatim cell, hand-verified anchors
# ════════════════════════════════════════════════════════════════════════════

def test_real_register_parses_and_finds_active_table():
    rows = _dp_table()
    assert len(rows) == _join()["register_row_count"], "parsed row count drifted from fixture"
    assert len(rows) > 250, f"only {len(rows)} active rows — parser/layout regression?"


def test_named_anchors_have_correct_no_file_date_and_manufacturer():
    by_name = {r["medicinal_ingredient"].strip().lower(): r for r in _dp_table()}
    for ing, (mfr, no_file) in _REGISTER_ANCHORS.items():
        row = by_name.get(ing)
        assert row is not None, f"{ing} missing from real Register fixture"
        assert row["manufacturer"] == mfr, (ing, row["manufacturer"])
        # The "6 Year No File Date" column — verbatim, not data_protection_ends.
        assert row["no_file_date"] == no_file, (ing, row["no_file_date"])
        assert row["data_protection_ends"] != row["no_file_date"], "columns must be distinct"


def test_every_register_no_file_date_parses_to_a_real_date():
    # The live Active table currently prints only real YYYY-MM-DD values; assert they
    # all normalize to genuine dates (N/A/footnote handling is unit-tested in
    # test_screen_filters against synthetic strings, since the table has none today).
    for r in _dp_table():
        assert parse_stored_no_file_date(r["no_file_date"]) is not None, r["no_file_date"]


# ════════════════════════════════════════════════════════════════════════════
# Attach correctness — right DIN, blank when absent, no false near-miss attach
# ════════════════════════════════════════════════════════════════════════════

def test_matched_products_attach_their_real_date():
    dp = _dp_table()
    matched = _join()["matched"]
    assert len(matched) > 100, "fixture should carry the full real matched set"
    # Spot-check every matched product reproduces its recorded attach via the matcher.
    for p in matched:
        cols = _get_dp_cols(p["ingredient"], p["company"], dp)
        assert cols["dp_6yr_no_file_date"] == p["expected_no_file_date"], p["din"]


def test_named_innovator_din_carries_hand_verified_date():
    dp = _dp_table()
    matched = {m["din"]: m for m in _join()["matched"]}
    # alpelisib / PIQRAY — Novartis. DIN + date pinned from the live Register.
    piqray = matched.get("02497069")
    assert piqray is not None, "expected alpelisib DIN 02497069 in the matched fixture"
    assert "NOVARTIS" in (piqray["company"] or "").upper()
    cols = _get_dp_cols(piqray["ingredient"], piqray["company"], dp)
    assert cols["dp_6yr_no_file_date"] == "2026-03-11"


def test_no_register_product_stays_blank():
    dp = _dp_table()
    blanks = _join()["blank"]
    assert blanks, "fixture should carry no-Register generics"
    for p in blanks:
        cols = _get_dp_cols(p["ingredient"], p["company"], dp)
        assert not cols["dp_6yr_no_file_date"], (p["din"], cols["dp_6yr_no_file_date"])


def test_near_miss_manufacturer_does_not_get_false_date():
    """Products sharing an ingredient with a Register row but a DIFFERENT
    manufacturer must NOT inherit that row's date."""
    dp = _dp_table()
    near = _join()["near_miss"]
    assert near, "fixture should carry near-miss (ingredient-overlap, wrong mfr) cases"
    for p in near:
        cols = _get_dp_cols(p["ingredient"], p["company"], dp)
        assert not cols["dp_6yr_no_file_date"], (
            f"false attach: DIN {p['din']} ({p['ingredient']!r}/{p['company']!r}) "
            f"got {cols['dp_6yr_no_file_date']!r}"
        )


# ════════════════════════════════════════════════════════════════════════════
# Fuzzy-match-at-scale guard (deterministic on the offline join fixture)
# ════════════════════════════════════════════════════════════════════════════

def _attached() -> list[dict]:
    """Re-run the matcher over EVERY fixture product (matched + near_miss + blank)
    against the real Register; return the rows that received a date."""
    dp = _dp_table()
    join = _join()
    out = []
    for bucket in ("matched", "near_miss", "blank"):
        for p in join[bucket]:
            cols = _get_dp_cols(p["ingredient"], p["company"], dp)
            d = (cols.get("dp_6yr_no_file_date") or "").strip()
            if d:
                out.append({**p, "attached": d})
    return out


def test_no_fabricated_dates_in_join():
    dp = _dp_table()
    register_dates = {r["no_file_date"].strip() for r in dp}
    attached_dates = {a["attached"] for a in _attached()}
    fabricated = attached_dates - register_dates
    assert not fabricated, f"attached dates absent from the Register (fabricated): {fabricated}"


def test_distinct_attached_identities_do_not_exceed_register_rows():
    dp = _dp_table()
    attached = _attached()
    identities = {(NI(a["ingredient"] or ""), NM(a["company"] or "")) for a in attached}
    # You cannot attach more distinct (ingredient, manufacturer) identities than the
    # Register holds rows — a blowup past this means the fuzzy match is inventing hits.
    assert len(identities) <= len(dp), (len(identities), len(dp))


def test_fanout_per_register_row_is_bounded():
    fan = Counter((a["attached"], NM(a["company"] or "")) for a in _attached())
    worst = max(fan.values()) if fan else 0
    assert worst <= _FANOUT_CEILING, (
        f"a (date, manufacturer) identity fanned out to {worst} DINs "
        f"(> {_FANOUT_CEILING}) — likely a fuzzy-match blowup"
    )


def test_every_attached_din_shares_its_register_identity():
    """No cross-attach: each attached DIN must trace to a Register row with the same
    date, an overlapping normalized ingredient, and an exact-or-fuzzy(≥0.8)
    normalized manufacturer (the same join the matcher is allowed to make)."""
    dp = _dp_table()
    incoherent = []
    for a in _attached():
        ni, nc, d = NI(a["ingredient"] or ""), NM(a["company"] or ""), a["attached"]
        candidates = [r for r in dp if r["no_file_date"].strip() == d
                      and (NI(r["medicinal_ingredient"]) in ni or ni in NI(r["medicinal_ingredient"]))]
        mfrs = [NM(r["manufacturer"]) for r in candidates]
        ok = nc in mfrs or bool(get_close_matches(nc, mfrs, n=1, cutoff=0.8))
        if not ok:
            incoherent.append((a["din"], ni, nc, d))
    assert not incoherent, f"attached DINs with no matching Register identity: {incoherent[:8]}"
